# Generated by Django 5.1.1 on 2024-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
