# Generated by Django 5.1.1 on 2024-10-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_upload_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url',
        ),
    ]
