# Generated by Django 5.1.1 on 2024-10-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_upload_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='url',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
