# Generated by Django 5.1.1 on 2024-10-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_upload_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='url',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
